version: "3.9"

services:
#  Можно закомментить только app и запустить приложение через ide
  app:
    container_name: 'expense-tracker'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-expenses_api}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  postgres:
    image: postgres:latest
    container_name: 'postgres'
    environment:
      POSTGRES_DB: expenses_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "5431:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: 'redis'
    hostname: 'redis'
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/var/lib/redis/data

volumes:
  postgres_volume:
  redis_volume:
